---
title: "xaringanExtra"
output:
  html_document:
    theme: null
    mathjax: null
    highlight: null
    code_folding: none
    template: ../xExtra/xExtra.html
    lib_dir: libs
    self_contained: false
---

```{r setup, include=FALSE, cache = FALSE}
options(htmltools.dir.version = FALSE, eval = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```

```{r xaringan-extra, echo=FALSE}
  xaringanExtra::use_xaringan_extra(include = params$xExtra_use)
```

```{r style-share-again, echo=FALSE}
xaringanExtra::style_share_again(
  share_buttons = c("twitter"),
  background = "#009C49",
  foreground = "#FFFFFF"
)
```

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "https://raw.githubusercontent.com/CenterForAssessment/cfaDocs/main/inst/rmarkdown/templates/xaringan/resources/img/CFA_Logo.svg", # could be local if copied to `libs`
  width = "86px",
  height = "100px",
  position = xaringanExtra::css_position(top = "0.5em", right = "0.5em"),
  link_url = "https://www.nciea.org"
)
```